### ISSUE TITLE
How can I generate the plots shown in the blog post?

### ISSUE THREAD

**Issue by LeenaShekhar** [fractalego/chatbots-dialogues-test#2]
In the blog post: https://medium.com/@fractalego/representing-dialogues-43aa43352e25 , last few graphs, mainly the one showing path in the sentence vector space are pretty good. 

How can I generate those using this code?

**Comment by fractalego** [comment]
I just updated generate_dialogues.py. The system now generates a conversation and plots the path. Once you close the plot window the system generates another conversation.

Your results may differ from the blog plots, there is plenty of random seeds in the trained vectors and dialogues (In my latest training set the dialogues tend to be longer).

The plotting lines are 161-164 in generate_dialogues.py

Let me know if you have any problem setting up the system. Admittedly, this code is rushed and would need a refactor (it is still a work in progress).

I also added a disclaimer in the README. The movie lines are taken from the Cornell movie corpus and I did not modify them nor looked for offensive lines.

**Comment by LeenaShekhar** [comment]
Thank you. Let me take an update and close this thread by tonight. 

I will raise issues if I find any so that it helps you to refactor he code.

**Comment by LeenaShekhar** [comment]
I can see the plots now. I will close this thread. Thank you.

**Comment by LeenaShekhar** [comment]
Two suggestions for the plots:
1. plt.savefig(fname) rather than plt.show() to keep generating in generate_dialogues.py.py and clustering.py.
2. to run with python2:
    2.1 use 
import io, then io.open() rather than open()

    2.2 use the following lines in generate_dialogues.py and  plot_chat_path.py file. 
import matplotlib
matplotlib.use('agg')

**Comment by fractalego** [comment]
Thanks! I will implement them.
